version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: college-db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Password!given
      MYSQL_DATABASE: collegedb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-prod:
    image: mysql:8.0
    container_name: college-db
    environment:
      MYSQL_ROOT_USER: adminvoice
      MYSQL_ROOT_PASSWORD: 'psql$voice'
      MYSQL_USER: adminvoice
      MYSQL_PASSWORD: 'psql$voice'
      MYSQL_DATABASE: collegedb
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5

  # Development service
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: college-exam-api
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Password!given
      - DB_DATABASE=collegedb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    profiles:
      - dev
  #command: npm run start:dev

  # Development service
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: college-api-prod
    env_file:
      - ".env.production"
    ports:
      - ${EXTERNAL_APP_PORT}:${INTERNAL_APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db-prod
    #user: "appuser:appgroup"
    profiles:
      - prod
  #command: npm run start:dev

volumes:
  mysql_data:
  
# version: '3.8'

# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     network_mode: "host"  # This allows the container to access host network
#     environment:
#       - NODE_ENV=development
#       - DB_HOST=127.0.0.1
#       - DB_PORT=3306
#       - DB_USERNAME=root
#       - DB_PASSWORD=Password!given
#       - DB_DATABASE=nurse_exam_db
#     volumes:
#       - .:/app
#       - /app/node_modules
#     command: npm run start:dev


